# Project Configuration File
#
# A detailed documentation with the EXAMPLES is located here:
# http://docs.platformio.org/en/latest/projectconf.html
#

# A sign `#` at the beginning of the line indicates a comment
# Comment lines are ignored.


[application]
name = LvglSkeleton

[platformio]
boards_dir = .
default_envs = 
  desktop_sdl2_posix
  desktop_sdl2_windows
  crowpanel_esp32_5inch_v2


[env]
build_flags = 
  -Wall -pedantic -std=gnu++17 
  -D APPLICATION_NAME=\"${application.name}\"  
  -D LV_CONF_SKIP=1
  -D LV_LVGL_H_INCLUDE_SIMPLE=1
  -D LV_USE_LOG=1
  -D LV_LOG_LEVEL=LV_LOG_LEVEL_WARN
  -D LV_FONT_MONTSERRAT_18=1
  -D LV_FONT_MONTSERRAT_24=1
  -D LV_FONT_MONTSERRAT_48=1
  -D LV_DRAW_SW_SUPPORT_ARGB8888=1 ; needed for indexed images
  -D LV_USE_KEYBOARD=1
build_unflags = 
  -std=gnu++11    
monitor_speed = 
  115200  
lib_deps = 
  lvgl/lvgl@9.3
  nanopb/Nanopb@^0.4.91
#extra_scripts = pre:extra_script.py ; needed for creating the compile_commands.json file for sonarQube analysis


#####################################################################
# Native environment is used for testing                            #
# It can be used for running unit tests with Google Test framework. #
#####################################################################

[native_base]
platform = native
lib_compat_mode = off        ; for beeing able to use arduino libraries in native environment
test_ignore = test_*_gtest

[env:native]
extends = native_base
extra_scripts =
  pre:support/native_build_extra.py
build_flags = 
  ${env.build_flags}
  -D LV_USE_OS=LV_OS_NONE
build_unflags = ${env.build_unflags} -pedantic ; -pedantic does not work because of the framework  
build_src_filter = 
	+<../hal/main_plain>
	+<*>      


############################################################################
# ESP32 environment is used for testing and running on the ESP32 platform  #
############################################################################

[esp32_base]
platform = espressif32
framework = arduino
platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#2.0.3
build_unflags = ${env.build_unflags} -pedantic ; -pedantic does not work because of the framework
test_ignore = test_*_gtest
debug_tool = esp-prog
debug_init_break = 
  tbreak setup   
upload_speed = 460800  ; more does not work with my mac mini and the esp-prog


[env:crowpanel_esp32_5inch_v2]
extends = esp32_base
board = crowpanel_esp32_5inch_v2
board_build.partitions = huge_app.csv
board_upload.maximum_size = 3145728
build_flags = 
  ${env.build_flags} 
  -D LV_USE_OS=LV_OS_FREERTOS
	-I hal/datastorage_esp32
	-I hal/ui_crowpanel
	-I hal/wifi_esp32
  -I hal/mqtt_arduino
  -I hal/lightstripe_dummy
  -D configSUPPORT_STATIC_ALLOCATION=1
lib_deps = ${env.lib_deps}
	lovyan03/LovyanGFX@^1.1.12
  arduino-libraries/ArduinoMqttClient
build_src_filter =   
	+<../hal/main_arduino>
  +<../hal/wifi_esp32>
  +<../hal/mqtt_arduino>
	+<../hal/ui_crowpanel>
  +<../hal/lightstripe_dummy>
  +<../hal/datastorage_esp32>
	+<*>


##########################################################################
# Desktop environment is used for running the application on the desktop #
##########################################################################

[desktop_base]
extends = native_base
extra_scripts =
  post:support/sdl2_build_extra.py
build_flags =
	${env.build_flags}
	-D LV_USE_OS=LV_OS_FREERTOS
	-DLV_LOG_PRINTF=1
  -I hal/arduino_compat
  -I hal/freertos_desktop/include
  -I hal/freertos_desktop/kernel/include
  -I hal/datastorage_file
  -I hal/ui_sdl2
  -I hal/os_desktop
  -I hal/wifi_dummy
  -I hal/mqtt_dummy
  -I hal/lightstripe_dummy
  -D configSUPPORT_STATIC_ALLOCATION=1
	-lSDL2
	; SDL drivers options
  -D LV_DRV_NO_CONF
  -D LV_USE_SDL
  -D LV_MEM_SIZE=131072 ; 128 kB
  ;-D SDL_HOR_RES=480
  ;-D SDL_VER_RES=320
  ;-D SDL_ZOOM=1
  -D LV_SDL_INCLUDE_PATH="\"SDL2/SDL.h\""
build_src_filter =
	+<../hal/main_freertos>
  +<../hal/arduino_compat>
  +<../hal/freertos_hooks>
  +<../hal/os_desktop>
  +<../hal/wifi_dummy>
  +<../hal/mqtt_dummy>
  +<../hal/lightstripe_dummy>
	+<../hal/ui_sdl2>
  +<../hal/datastorage_file>
  +<../hal/freertos_desktop/kernel/tasks.c>
  +<../hal/freertos_desktop/kernel/queue.c>
  +<../hal/freertos_desktop/kernel/list.c>
  +<../hal/freertos_desktop/kernel/timers.c>
  +<../hal/freertos_desktop/kernel/event_groups.c>
  +<../hal/freertos_desktop/kernel/stream_buffer.c>
  +<../hal/freertos_desktop/kernel/portable/MemMang/heap_4.c>
	+<*>


[env:desktop_sdl2_windows]
extends = desktop_base
build_flags =
  ${desktop_base.build_flags}
  -I hal/freertos_desktop/kernel/portable/MSVC-MingW
  -I hal/freertos_desktop/config
  -lwinmm
build_src_filter =
  ${desktop_base.build_src_filter}
  +<../hal/freertos_desktop/kernel/portable/MSVC-MingW/port.c>


[env:desktop_sdl2_posix]
extends = desktop_base
extra_scripts =
  pre:support/sdl2_paths.py
  post:support/sdl2_build_extra.py
build_flags =
  ${desktop_base.build_flags}
  -I hal/freertos_desktop/kernel/portable/ThirdParty/GCC/Posix
  -I hal/freertos_desktop/config_posix
  -lpthread
build_src_filter =
  ${desktop_base.build_src_filter}
  +<../hal/freertos_desktop/kernel/portable/ThirdParty/GCC/Posix/port.c>
  +<../hal/freertos_desktop/kernel/portable/ThirdParty/GCC/Posix/utils/wait_for_event.c>
