# Project Configuration File
#
# A detailed documentation with the EXAMPLES is located here:
# http://docs.platformio.org/en/latest/projectconf.html
#

# A sign `#` at the beginning of the line indicates a comment
# Comment lines are ignored.


[application]
name = LvglSkeleton

[platformio]
boards_dir = .
default_envs = 
  emulator_64bits
  crowpanel_esp32_5inch_v2

[native_base]
platform = native
lib_compat_mode = off        ; for beeing able to use arduino libraries in native environment
test_ignore = test_*_gtest

[esp32_base]
platform = espressif32
framework = arduino
platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#2.0.3
build_unflags = ${env.build_unflags} -pedantic ; -pedantic does not work because of the framework
test_ignore = test_*_gtest
debug_tool = esp-prog
debug_init_break = 
  tbreak setup   



[env]
build_flags = 
  -Wall -pedantic -std=gnu++17 -DAPPLICATION_NAME=\"${application.name}\"
  -D LV_CONF_SKIP
  -D LV_CONF_INCLUDE_SIMPLE
  -D LV_USE_DEMO_WIDGETS=1
  -D LV_USE_PERF_MONITOR=1  
build_unflags = 
  -std=gnu++11    
monitor_speed = 
  115200  
lib_deps = 
  lvgl/lvgl@8
#extra_scripts = pre:extra_script.py ; needed for creating the compile_commands.json file for sonarQube analysis


[env:crowpanel_esp32_5inch_v2]
extends = esp32_base
board = crowpanel_esp32_5inch_v2
build_flags = 
  ${env.build_flags} 
  -D LV_LOG_LEVEL=LV_LOG_LEVEL_NONE
lib_deps = ${env.lib_deps}
	lovyan03/LovyanGFX@^1.1.12
build_src_filter =   
	+<*>
	+<../hal/crowpanel>


[env:emulator_64bits]
extends = native_base
extra_scripts = 
  pre:support/sdl2_paths.py ; Tries to find SDL2 include and lib paths on your system - specifically for MacOS w/ Homebrew
  post:support/sdl2_build_extra.py
build_flags = 
	${env.build_flags}
	!python -c "import os; print(' '.join(['-I {}'.format(i[0].replace('\x5C','/')) for i in os.walk('hal/sdl2')]))"
	-lSDL2
	; SDL drivers options
  -D LV_LVGL_H_INCLUDE_SIMPLE
  -D LV_DRV_NO_CONF
  -D LV_SDL_INCLUDE_PATH="\"SDL2/SDL.h\""
  ;-D LV_USE_LOG=1
  ;-D LV_LOG_LEVEL=LV_LOG_LEVEL_INFO
build_src_filter = 
	+<*>
	+<../hal/sdl2>
