# Project Configuration File
#
# A detailed documentation with the EXAMPLES is located here:
# http://docs.platformio.org/en/latest/projectconf.html
#

# A sign `#` at the beginning of the line indicates a comment
# Comment lines are ignored.


[application]
name = LvglSkeleton

[platformio]
boards_dir = .
default_envs = 
  desktop_sdl2
  crowpanel_esp32_5inch_v2

[native_base]
platform = native
lib_compat_mode = off        ; for beeing able to use arduino libraries in native environment
test_ignore = test_*_gtest

[esp32_base]
platform = espressif32
framework = arduino
platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#2.0.3
build_unflags = ${env.build_unflags} -pedantic ; -pedantic does not work because of the framework
test_ignore = test_*_gtest
debug_tool = esp-prog
debug_init_break = 
  tbreak setup   
upload_speed = 460800  ; more does not work with my mac mini and the esp-prog


[env]
build_flags = 
  -Wall -pedantic -std=gnu++17 
  -D APPLICATION_NAME=\"${application.name}\"  
  -D LV_CONF_SKIP=1
  -D LV_LVGL_H_INCLUDE_SIMPLE=1
  -D LV_USE_LOG=1
  -D LV_LOG_LEVEL=LV_LOG_LEVEL_INFO
  -D LV_FONT_MONTSERRAT_18=1
  -D LV_DRAW_SW_SUPPORT_ARGB8888=1 ; needed for indexed images
build_unflags = 
  -std=gnu++11    
monitor_speed = 
  115200  
lib_deps = 
  lvgl/lvgl@9.3
#extra_scripts = pre:extra_script.py ; needed for creating the compile_commands.json file for sonarQube analysis



[env:native]
extends = native_base
build_flags = 
  ${env.build_flags}
build_unflags = ${env.build_unflags} -pedantic ; -pedantic does not work because of the framework  
build_src_filter = 
	+<../hal/main_plain>
	+<*>      


[env:crowpanel_esp32_5inch_v2]
extends = esp32_base
board = crowpanel_esp32_5inch_v2
build_flags = 
  ${env.build_flags} 
	!python -c "import os; print(' '.join(['-I {}'.format(i[0].replace('\x5C','/')) for i in os.walk('hal/datastorage_esp32')]))"
	!python -c "import os; print(' '.join(['-I {}'.format(i[0].replace('\x5C','/')) for i in os.walk('hal/ui_crowpanel')]))"  
	!python -c "import os; print(' '.join(['-I {}'.format(i[0].replace('\x5C','/')) for i in os.walk('hal/os_freertos')]))"  
	!python -c "import os; print(' '.join(['-I {}'.format(i[0].replace('\x5C','/')) for i in os.walk('hal/wifi_esp32')]))"  
  -D LV_USE_LOG=1
  -D LV_LOG_LEVEL=LV_LOG_LEVEL_INFO
  -D LV_USE_OS=LV_OS_FREERTOS
  -D LV_USE_KEYBOARD=1
  -D configSUPPORT_STATIC_ALLOCATION=1
lib_deps = ${env.lib_deps}
	lovyan03/LovyanGFX@^1.1.12
  https://github.com/steftri/8BitFonts
build_src_filter =   
	+<../hal/main_arduino>
	+<../hal/os_freertos>
  +<../hal/wifi_esp32>
	+<../hal/ui_crowpanel>
  +<../hal/datastorage_esp32>
	+<*>


[env:desktop_sdl2]
extends = native_base
extra_scripts = 
  pre:support/sdl2_paths.py ; Tries to find SDL2 include and lib paths on your system - specifically for MacOS w/ Homebrew
  post:support/sdl2_build_extra.py
build_flags = 
	${env.build_flags}
	-DLV_LOG_PRINTF=1
	!python -c "import os; print(' '.join(['-I {}'.format(i[0].replace('\x5C','/')) for i in os.walk('hal/datastorage_file')]))"
	!python -c "import os; print(' '.join(['-I {}'.format(i[0].replace('\x5C','/')) for i in os.walk('hal/ui_sdl2')]))"
	!python -c "import os; print(' '.join(['-I {}'.format(i[0].replace('\x5C','/')) for i in os.walk('hal/os_desktop')]))"   
	!python -c "import os; print(' '.join(['-I {}'.format(i[0].replace('\x5C','/')) for i in os.walk('hal/wifi_dummy')]))"   
	-lSDL2
	; SDL drivers options
  -D LV_DRV_NO_CONF
  -D LV_USE_SDL
  -D LV_MEM_SIZE=(128*1024)
  -D SDL_HOR_RES=480
  -D SDL_VER_RES=320  
  -D SDL_ZOOM=1
  -D LV_SDL_INCLUDE_PATH="\"SDL2/SDL.h\""
build_src_filter = 
	+<../hal/main_plain>
  +<../hal/os_desktop>
  +<../hal/wifi_dummy>
	+<../hal/ui_sdl2>
  +<../hal/datastorage_file>
	+<*>
