// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Porsche_SquareLine_Project

#ifndef _PORSCHE_SQUARELINE_PROJECT_UI_H
#define _PORSCHE_SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_PorscheLogo;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabInfo;
extern lv_obj_t * ui_TabHistory;
extern lv_obj_t * ui_TabSettings;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_WiFi;
extern lv_obj_t * ui_WiFiName;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_2101743285);    // assets/porsche-logo_200x258.png
LV_IMG_DECLARE(ui_img_1765738);    // assets/ERNI-inside_inverted.png
LV_IMG_DECLARE(ui_img_1024807844);    // assets/info-icon_40x40.png
LV_IMG_DECLARE(ui_img_1638332441);    // assets/settings-icon_48x48.png
LV_IMG_DECLARE(ui_img_menubar_normal_368x64_png);    // assets/Menubar_normal_368x64.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
