// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Porsche_SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PorscheLogo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_PorscheLogo, &ui_img_2101743285);
    lv_obj_set_width(ui_PorscheLogo, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_PorscheLogo, LV_SIZE_CONTENT);    /// 258
    lv_obj_set_x(ui_PorscheLogo, 0);
    lv_obj_set_y(ui_PorscheLogo, -64);
    lv_obj_set_align(ui_PorscheLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PorscheLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PorscheLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_1765738);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 108
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, 156);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
