// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Porsche_SquareLine_Project

#include <stdio.h>

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);

    lv_obj_t * tabview;
    tabview = lv_tabview_create(ui_Screen3, LV_DIR_BOTTOM, 96);

    //lv_obj_set_style_bg_color(tabview, lv_palette_lighten(LV_PALETTE_RED, 2), 0);

    lv_obj_t * tab_btns = lv_tabview_get_tab_btns(tabview);
    lv_obj_set_style_bg_color(tab_btns, lv_palette_darken(LV_PALETTE_GREY, 3), 0);
    lv_obj_set_style_text_color(tab_btns, lv_palette_lighten(LV_PALETTE_GREY, 5), 0);
    lv_obj_set_style_border_side(tab_btns, LV_BORDER_SIDE_TOP, LV_PART_ITEMS | LV_STATE_CHECKED);


    lv_obj_set_style_bg_img_src(tab_btns, &ui_img_menubar_normal_368x64_png, LV_PART_MAIN);
    //lv_obj_set_style_bg_img_src(tab_btns, &ui_img_486792032, LV_PART_MAIN);


    /*Add 3 tabs (the tabs are page (lv_page) and can be scrolled*/
    lv_obj_t * tab1 = lv_tabview_add_tab(tabview, " ");
    lv_obj_t * tab2 = lv_tabview_add_tab(tabview, " ");
    lv_obj_t * tab3 = lv_tabview_add_tab(tabview, " ");

    

    /*Add content to the tabs*/
    lv_obj_t * label = lv_label_create(tab1);
    lv_label_set_text(label, "Information tab");

    label = lv_label_create(tab2);
    lv_label_set_text(label, "History tab");

    label = lv_label_create(tab3);
    lv_label_set_text(label, "Settings tab");

    lv_obj_clear_flag(lv_tabview_get_content(tabview), LV_OBJ_FLAG_SCROLLABLE);
}
