/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MODEL_PROTOBUF_MQTTMESSAGES_PB_H_INCLUDED
#define PB_MODEL_PROTOBUF_MQTTMESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _TempHumSensor {
    uint32_t timestamp;
    float temperature;
    uint32_t humidity;
} TempHumSensor;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TempHumSensor_init_default               {0, 0, 0}
#define TempHumSensor_init_zero                  {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define TempHumSensor_timestamp_tag              1
#define TempHumSensor_temperature_tag            2
#define TempHumSensor_humidity_tag               3

/* Struct field encoding specification for nanopb */
#define TempHumSensor_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   timestamp,         1) \
X(a, STATIC,   REQUIRED, FLOAT,    temperature,       2) \
X(a, STATIC,   REQUIRED, UINT32,   humidity,          3)
#define TempHumSensor_CALLBACK NULL
#define TempHumSensor_DEFAULT NULL

extern const pb_msgdesc_t TempHumSensor_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TempHumSensor_fields &TempHumSensor_msg

/* Maximum encoded size of messages (where known) */
#define MODEL_PROTOBUF_MQTTMESSAGES_PB_H_MAX_SIZE TempHumSensor_size
#define TempHumSensor_size                       17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
