name: PlatformIO Native Unit Tests

on:
  push:
  pull_request:

jobs:
  native-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PlatformIO
        run: |
          python -m pip install platformio

      - name: Run PlatformIO native unit tests
        run: platformio test --environment native
